language: c
compiler:
    - clang
    - gcc
install:
    - sudo add-apt-repository --yes ppa:kalakris/cmake
    - sudo apt-get -qq update
    - sudo apt-get -qq install -y cmake
script: cmake . && make
